name: "Release Customer Impact Summary"
description: "GitHub Action that generates a customer impact summary for a release"
author: "uman.ai"
runs:
  using: "node20"
  main: "dist/index.js"
inputs:
  github_token:
    description: "The GITHUB_TOKEN secret"
    required: true
  google_gemini_api_key:
    description: "The Google Gemini API key"
    required: true
outputs:
  customer_impact_prompt:
    description: "The prompt that was sent to Gemini AI for generating the customer impact summary"
branding:
  icon: git-pull-request
  color: green
