name: "Prerelease Changelog"
description: "GitHub Action that generates a prerelease changelog"
author: "uman.ai"
runs:
  using: "node12"
  main: "dist/index.js"
inputs:
  github_token:
    description: "The GITHUB_TOKEN secret"
    required: true
  is_prerelease:
    description: "Whether the PR is part of a prerelease"
    default: "false"

branding:
  icon: git-pull-request
  color: green
